apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  sources:
    - repoURL: 'https://aws.github.io/eks-charts'
      chart: aws-load-balancer-controller
      targetRevision: 1.8.1
      helm:
        valueFiles:
          - $values/_applications/system/alb-controller/values.yaml
    - repoURL: https://github.com/presentium/kubernetes.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
