apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        iops: 3000
        throughput: 125
        volumeSize: 20Gi
        volumeType: gp3
  role: PRES-KARPENTER-PRESENTIUM
  securityGroupSelectorTerms:
    - tags:
        Name: eks-cluster-sg-presentium-*
  subnetSelectorTerms:
    - id: "subnet-0381bfb78583d2908"
    - id: "subnet-051408f2921d9c4f4"
    - id: "subnet-0da26b22c86f4b2b8"
  tags:
    Managed_By: karpenter
    karpenter.sh/discovery: presentium
