apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: on-demand
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
  limits:
    cpu: 16
  template:
    spec:
      kubelet:
        maxPods: 110
        podsPerCore: 16
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: [ 'amd64' ]
        - key: kubernetes.io/os
          operator: In
          values: [ 'linux' ]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: [ 't3a' ]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: [ '2' ]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: [ 'medium' ]
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values: [ 'nitro' ]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [ 'on-demand' ]
