creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    unencrypted_regex: "^(kind)$"
    kms: 'arn:aws:kms:eu-west-1:123247571664:alias/presentium/sops'
    age: >-
      age1889ep8dshl0c50e4a05j2ny7z64h3qdpcprx3v2fqqe5r67ln9nqjfj3ae
