apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  source:
    repoURL: https://github.com/presentium/kubernetes
    targetRevision: HEAD
    path: system/karpenter
  destination:
    name: in-cluster
    namespace: karpenter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
