apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.28.1
    helm:
      valuesFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
