apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: vault-csr
spec:
  signerName: beta.eks.amazonaws.com/app-serving
  request: {{ .Values.tls.csr.request | b64enc }}
  groups:
    - system:serviceaccounts
    - system:serviceaccounts:argocd
    - system:authenticated
  usages:
    - digital signature
    - key encipherment
    - server auth
