apiVersion: v1
kind: Secret
metadata:
  name: tls-server
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate.crt | b64enc }}
  tls.key: {{ .Values.tls.certificate.key | b64enc }}
