authentik:
  error_reporting:
    enabled: false

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: alb
    hosts:
      - sso.presentium.ch

worker:
  replicas: 1

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    kind: Deployment
    persistence:
      enabled: false
