authentik:
  error_reporting:
    enabled: false
  email:
    host: 'email-smtp.eu-west-1.amazonaws.com'
    port: 587
    from: 'Presentium Authentik <no-reply+authentik@presentium.ch>'
    use_ssl: false
    use_tls: true

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /-/health/ready/
      alb.ingress.kubernetes.io/success-codes: 200,204
    hosts:
      - sso.presentium.ch

worker:
  replicas: 1

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    kind: Deployment
    persistence:
      enabled: false
