apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  source:
    repoURL: 'https://charts.goauthentik.io/'
    chart: authentik
    targetRevision: 2024.6.2
    helm:
      valuesFiles:
        - values.yaml
        - secrets://secrets.sops.yaml
  destination:
    name: in-cluster
    namespace: core-authentik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
