apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  sources:
    - repoURL: 'https://charts.goauthentik.io/'
      chart: authentik
      targetRevision: 2024.6.3
      helm:
        valueFiles:
          - $values/_applications/core/authentik/values.yaml
          - $values/_applications/core/authentik/secrets.sops.yaml
    - repoURL: https://github.com/presentium/kubernetes.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: authentik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
