apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: presentium
spec:
  generators:
    - scmProvider:
        filters:
          - repositoryMatch: ^api
            pathsExist: [ kubernetes/kustomization.yaml ]
            labelMatch: deploy
            branchMatch: main
        github:
          organization: presentium
  template:
    metadata:
      name: 'presentium-{{ .repository }}'
    spec:
      source:
        repoURL: '{{ .url }}'
        targetRevision: '{{ .branch }}'
        path: kubernetes/
      project: presentium
      destination:
        server: https://kubernetes.default.svc
        namespace: presentium
