apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.vault-deployed.github: ""
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  source:
    repoURL: 'https://github.com/presentium/kubernetes.git'
    targetRevision: HEAD
    path: core/vault
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets.sops.yaml
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
