apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.vault-deployed.github: ""
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: global
  sources:
    - repoURL: 'https://helm.releases.hashicorp.com'
      chart: vault-helm
      targetRevision: 0.28.1
      helm:
        valueFiles:
          - $values/core/vault/values.yaml
    - repoURL: https://github.com/presentium/kubernetes.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
